export interface Achievement {
  id: number;
  title: string;
  description: string;
  xp: number;
}

const achievementsByArea: Record<string, Achievement[]> = {
  FullStack: [
    { id: 1, title: "Estruturar uma página web", description: "Crie uma página usando HTML semântico e organize seu conteúdo.", xp: 25 },
    { id: 2, title: "Estilizar uma interface", description: "Use CSS para criar um layout responsivo para diferentes telas.", xp: 25 },
    { id: 3, title: "Adicionar interatividade", description: "Implemente uma interação de usuário usando JavaScript.", xp: 25 },
    { id: 4, title: "Construir um componente", description: "Crie e reutilize componentes com React.", xp: 25 },
    { id: 5, title: "Conectar uma API", description: "Consuma uma API e exiba os dados em uma interface.", xp: 25 },
    { id: 6, title: "Persistir dados", description: "Implemente uma funcionalidade que salve e recupere dados.", xp: 25 },
    { id: 7, title: "Versionar um projeto", description: "Publique seu código em um repositório Git e registre suas alterações.", xp: 25 },
    { id: 8, title: "Publicar uma aplicação", description: "Faça o deploy de uma aplicação web e compartilhe o link.", xp: 25 },
    { id: 9, title: "Criar uma página acessível", description: "Use HTML semântico, textos alternativos e navegação por teclado.", xp: 25 },
    { id: 10, title: "Validar formulários", description: "Implemente validação no cliente e apresente mensagens de erro claras.", xp: 25 },
    { id: 11, title: "Construir uma API", description: "Crie rotas REST para consultar e alterar recursos da aplicação.", xp: 25 },
    { id: 12, title: "Modelar um banco de dados", description: "Defina tabelas, relacionamentos e restrições para os dados do projeto.", xp: 25 },
    { id: 13, title: "Implementar autenticação", description: "Adicione um fluxo seguro de cadastro, login e logout.", xp: 25 },
    { id: 14, title: "Proteger rotas", description: "Restrinja páginas e operações a usuários autenticados e autorizados.", xp: 25 },
    { id: 15, title: "Adicionar testes automatizados", description: "Escreva testes para componentes ou rotas importantes da aplicação.", xp: 25 },
    { id: 16, title: "Tratar estados de carregamento", description: "Mostre estados de carregamento, sucesso e erro ao buscar dados.", xp: 25 },
    { id: 17, title: "Otimizar desempenho", description: "Identifique e melhore um gargalo de carregamento ou renderização.", xp: 25 },
    { id: 18, title: "Configurar variáveis de ambiente", description: "Separe configurações por ambiente sem expor segredos no código.", xp: 25 },
    { id: 19, title: "Documentar a API", description: "Descreva endpoints, parâmetros, respostas e erros da sua API.", xp: 25 },
    { id: 20, title: "Entregar um projeto fullstack", description: "Integre frontend, backend e persistência em uma aplicação publicada.", xp: 25 },
  ],
  QA: [
    { id: 1, title: "Estudar fundamentos de QA", description: "Identifique os objetivos de qualidade e as etapas do ciclo de testes.", xp: 25 },
    { id: 2, title: "Escrever casos de teste", description: "Documente cenários, passos e resultados esperados para uma funcionalidade.", xp: 25 },
    { id: 3, title: "Executar testes exploratórios", description: "Explore uma aplicação e registre os comportamentos observados.", xp: 25 },
    { id: 4, title: "Registrar um defeito", description: "Crie um relato de bug com passos para reprodução e evidências.", xp: 25 },
    { id: 5, title: "Testar uma API", description: "Valide respostas, códigos HTTP e dados de uma API usando Postman.", xp: 25 },
    { id: 6, title: "Automatizar um teste de interface", description: "Crie um teste automatizado de fluxo de usuário usando Cypress.", xp: 25 },
    { id: 7, title: "Criar um teste unitário", description: "Escreva e execute um teste unitário usando JUnit ou ferramenta equivalente.", xp: 25 },
    { id: 8, title: "Executar uma regressão", description: "Repita testes relevantes após uma alteração e documente os resultados.", xp: 25 },
    { id: 9, title: "Aplicar técnicas de teste", description: "Use particionamento de equivalência e análise de valor-limite em um cenário.", xp: 25 },
    { id: 10, title: "Testar caminhos alternativos", description: "Crie cenários para fluxos válidos, inválidos e casos de exceção.", xp: 25 },
    { id: 11, title: "Validar compatibilidade", description: "Verifique uma funcionalidade em navegadores ou dispositivos diferentes.", xp: 25 },
    { id: 12, title: "Verificar acessibilidade", description: "Avalie teclado, contraste e nomes acessíveis em uma interface.", xp: 25 },
    { id: 13, title: "Usar mocks e stubs", description: "Isole uma dependência externa para testar um componente de forma controlada.", xp: 25 },
    { id: 14, title: "Medir cobertura de testes", description: "Gere um relatório de cobertura e identifique lacunas importantes.", xp: 25 },
    { id: 15, title: "Automatizar testes de API", description: "Crie uma coleção de verificações automatizadas para endpoints.", xp: 25 },
    { id: 16, title: "Executar testes de integração", description: "Valide a interação entre módulos ou serviços do sistema.", xp: 25 },
    { id: 17, title: "Investigar uma falha", description: "Analise logs e evidências para encontrar a causa de um teste que falhou.", xp: 25 },
    { id: 18, title: "Integrar testes ao CI", description: "Configure a execução de testes automatizados em um pipeline.", xp: 25 },
    { id: 19, title: "Avaliar desempenho", description: "Execute um teste de carga simples e registre os tempos de resposta.", xp: 25 },
    { id: 20, title: "Planejar uma estratégia de QA", description: "Documente escopo, riscos, níveis de teste e critérios de saída.", xp: 25 },
  ],
  GameDev: [
    { id: 1, title: "Escolher uma engine", description: "Configure Unity, Godot ou outra engine para iniciar um projeto.", xp: 25 },
    { id: 2, title: "Criar uma cena jogável", description: "Monte uma cena com personagem, cenário e ponto inicial.", xp: 25 },
    { id: 3, title: "Programar controles", description: "Implemente movimento e controles básicos para o jogador.", xp: 25 },
    { id: 4, title: "Implementar uma mecânica", description: "Crie uma mecânica central, como pulo, coleta de itens ou combate.", xp: 25 },
    { id: 5, title: "Adicionar interface e feedback", description: "Exiba informações úteis e feedback visual ou sonoro durante o jogo.", xp: 25 },
    { id: 6, title: "Criar uma condição de vitória", description: "Implemente objetivos e uma condição para concluir uma partida.", xp: 25 },
    { id: 7, title: "Testar e ajustar o jogo", description: "Peça feedback, corrija problemas e ajuste a dificuldade.", xp: 25 },
    { id: 8, title: "Publicar uma versão jogável", description: "Gere uma build e compartilhe seu jogo para outras pessoas testarem.", xp: 25 },
    { id: 9, title: "Configurar colisões", description: "Adicione colisores e valide interações físicas entre objetos.", xp: 25 },
    { id: 10, title: "Criar animações", description: "Anime um personagem ou objeto e conecte a animação às ações do jogo.", xp: 25 },
    { id: 11, title: "Adicionar áudio", description: "Implemente música e efeitos sonoros para ações importantes.", xp: 25 },
    { id: 12, title: "Construir uma fase", description: "Crie uma fase com começo, desafio e objetivo claros.", xp: 25 },
    { id: 13, title: "Implementar sistema de pontuação", description: "Registre pontos ou recursos e apresente-os durante a partida.", xp: 25 },
    { id: 14, title: "Criar interface de pausa", description: "Implemente menus para pausar, retomar e reiniciar o jogo.", xp: 25 },
    { id: 15, title: "Salvar progresso", description: "Persista configurações ou progresso entre sessões do jogo.", xp: 25 },
    { id: 16, title: "Adicionar comportamento de inimigo", description: "Crie um comportamento simples de perseguição, patrulha ou reação.", xp: 25 },
    { id: 17, title: "Otimizar recursos da cena", description: "Reduza custos de renderização, física ou carregamento em uma cena.", xp: 25 },
    { id: 18, title: "Testar controles alternativos", description: "Verifique a experiência com diferentes entradas ou configurações.", xp: 25 },
    { id: 19, title: "Criar uma tela inicial", description: "Desenvolva um menu inicial com opções para começar e sair.", xp: 25 },
    { id: 20, title: "Finalizar um jogo completo", description: "Entregue um jogo com objetivo, começo, fim e build compartilhável.", xp: 25 },
  ],
  "Sistemas Embarcados": [
    { id: 1, title: "Conhecer os componentes", description: "Identifique microcontrolador, pinos, sensores e atuadores de uma placa.", xp: 25 },
    { id: 2, title: "Configurar o ambiente", description: "Instale e configure a IDE e as ferramentas da sua placa.", xp: 25 },
    { id: 3, title: "Executar o primeiro firmware", description: "Grave um programa simples no microcontrolador e valide sua execução.", xp: 25 },
    { id: 4, title: "Ler um sensor", description: "Capture dados de um sensor e interprete os valores recebidos.", xp: 25 },
    { id: 5, title: "Controlar um atuador", description: "Acione um LED, motor ou outro atuador a partir do firmware.", xp: 25 },
    { id: 6, title: "Depurar uma comunicação", description: "Use comunicação serial ou ferramenta de depuração para investigar o sistema.", xp: 25 },
    { id: 7, title: "Integrar hardware e software", description: "Combine sensor e atuador em uma solução embarcada funcional.", xp: 25 },
    { id: 8, title: "Documentar um protótipo", description: "Registre componentes, ligações e instruções para reproduzir seu protótipo.", xp: 25 },
    { id: 9, title: "Ler uma entrada analógica", description: "Converta a leitura de um pino analógico em um valor compreensível.", xp: 25 },
    { id: 10, title: "Usar interrupções", description: "Configure uma interrupção para responder a um evento de hardware.", xp: 25 },
    { id: 11, title: "Gerar PWM", description: "Controle brilho ou velocidade de um atuador usando PWM.", xp: 25 },
    { id: 12, title: "Comunicar por I2C ou SPI", description: "Conecte um periférico e troque dados usando um barramento serial.", xp: 25 },
    { id: 13, title: "Comunicar por UART", description: "Envie e receba dados entre a placa e outro dispositivo pela serial.", xp: 25 },
    { id: 14, title: "Organizar tarefas do firmware", description: "Separe responsabilidades do firmware em módulos ou tarefas claras.", xp: 25 },
    { id: 15, title: "Tratar falhas de sensores", description: "Detecte leituras inválidas e defina uma resposta segura do sistema.", xp: 25 },
    { id: 16, title: "Reduzir consumo de energia", description: "Aplique uma estratégia de baixo consumo e compare os resultados.", xp: 25 },
    { id: 17, title: "Armazenar configuração", description: "Salve e recupere parâmetros usando memória não volátil.", xp: 25 },
    { id: 18, title: "Conectar a uma rede", description: "Envie dados do dispositivo por Wi-Fi, Bluetooth ou outro protocolo.", xp: 25 },
    { id: 19, title: "Testar o protótipo", description: "Valide o circuito em diferentes condições e registre os resultados.", xp: 25 },
    { id: 20, title: "Montar um dispositivo funcional", description: "Integre placa, sensores, atuadores e firmware em um protótipo completo.", xp: 25 },
  ],
  "Robótica": [
    { id: 1, title: "Preparar o ambiente robótico", description: "Configure Linux, ROS ou as ferramentas da plataforma escolhida.", xp: 25 },
    { id: 2, title: "Entender nós e tópicos", description: "Execute nós e inspecione a comunicação por tópicos no ROS.", xp: 25 },
    { id: 3, title: "Publicar dados de um sensor", description: "Leia um sensor e disponibilize seus dados para outros componentes.", xp: 25 },
    { id: 4, title: "Controlar o movimento", description: "Envie comandos de movimento para um robô simulado ou físico.", xp: 25 },
    { id: 5, title: "Simular um robô", description: "Monte ou carregue um robô em um simulador e teste seus comandos.", xp: 25 },
    { id: 6, title: "Navegar em um ambiente", description: "Faça o robô seguir um caminho ou evitar obstáculos.", xp: 25 },
    { id: 7, title: "Integrar percepção e ação", description: "Use dados de sensores para orientar o comportamento do robô.", xp: 25 },
    { id: 8, title: "Demonstrar um projeto robótico", description: "Registre e compartilhe uma demonstração funcional do seu robô.", xp: 25 },
    { id: 9, title: "Descrever a estrutura do robô", description: "Defina links e juntas para representar a estrutura de um robô.", xp: 25 },
    { id: 10, title: "Visualizar transformações", description: "Inspecione a relação entre referenciais usando ferramentas do ROS.", xp: 25 },
    { id: 11, title: "Configurar odometria", description: "Estime a posição do robô a partir de sensores ou movimento das rodas.", xp: 25 },
    { id: 12, title: "Mapear um ambiente", description: "Gere ou carregue um mapa para uso em simulação ou navegação.", xp: 25 },
    { id: 13, title: "Planejar uma trajetória", description: "Defina um caminho seguro entre a posição inicial e um objetivo.", xp: 25 },
    { id: 14, title: "Integrar um sensor de distância", description: "Use dados de lidar ou sensor equivalente para detectar obstáculos.", xp: 25 },
    { id: 15, title: "Implementar controle de movimento", description: "Ajuste comandos do robô para seguir uma velocidade ou trajetória.", xp: 25 },
    { id: 16, title: "Usar localização do robô", description: "Estime a pose do robô em um mapa usando dados de sensores.", xp: 25 },
    { id: 17, title: "Diagnosticar nós do ROS", description: "Inspecione nós, tópicos e mensagens para localizar uma falha.", xp: 25 },
    { id: 18, title: "Testar em simulação", description: "Valide comportamento e segurança antes de executar no robô físico.", xp: 25 },
    { id: 19, title: "Adicionar parada de segurança", description: "Interrompa o movimento quando uma condição de risco for detectada.", xp: 25 },
    { id: 20, title: "Concluir uma missão robótica", description: "Faça o robô alcançar um objetivo usando percepção, planejamento e controle.", xp: 25 },
  ],
  "Data Science": [
    { id: 1, title: "Preparar o ambiente Python", description: "Configure Python e um ambiente para análise de dados.", xp: 25 },
    { id: 2, title: "Explorar um conjunto de dados", description: "Carregue dados com Pandas e investigue colunas e tipos.", xp: 25 },
    { id: 3, title: "Tratar dados ausentes", description: "Identifique inconsistências e documente como os dados foram tratados.", xp: 25 },
    { id: 4, title: "Criar visualizações", description: "Construa gráficos que comuniquem padrões relevantes dos dados.", xp: 25 },
    { id: 5, title: "Consultar dados com SQL", description: "Escreva consultas para filtrar, agrupar e relacionar informações.", xp: 25 },
    { id: 6, title: "Treinar um modelo", description: "Treine um modelo de machine learning para responder a uma pergunta.", xp: 25 },
    { id: 7, title: "Avaliar resultados", description: "Escolha métricas adequadas e avalie o desempenho do modelo.", xp: 25 },
    { id: 8, title: "Apresentar uma análise", description: "Comunique conclusões, limitações e próximos passos de um projeto de dados.", xp: 25 },
    { id: 9, title: "Definir uma pergunta analítica", description: "Transforme uma necessidade em uma pergunta que possa ser respondida com dados.", xp: 25 },
    { id: 10, title: "Coletar dados", description: "Carregue dados de arquivos, banco de dados ou uma fonte pública confiável.", xp: 25 },
    { id: 11, title: "Combinar fontes de dados", description: "Una tabelas compatíveis e valide as chaves usadas na combinação.", xp: 25 },
    { id: 12, title: "Analisar distribuições", description: "Calcule estatísticas descritivas e identifique valores fora do padrão.", xp: 25 },
    { id: 13, title: "Investigar correlações", description: "Explore relações entre variáveis sem confundir correlação com causalidade.", xp: 25 },
    { id: 14, title: "Criar um dashboard", description: "Monte um painel interativo com indicadores relevantes para uma pergunta.", xp: 25 },
    { id: 15, title: "Construir um pipeline de dados", description: "Automatize etapas repetíveis de carregamento, limpeza e transformação.", xp: 25 },
    { id: 16, title: "Selecionar variáveis", description: "Escolha atributos pertinentes e justifique sua inclusão no modelo.", xp: 25 },
    { id: 17, title: "Comparar modelos", description: "Avalie mais de um algoritmo usando a mesma divisão e métricas.", xp: 25 },
    { id: 18, title: "Evitar vazamento de dados", description: "Separe treino e avaliação corretamente para evitar métricas enganosas.", xp: 25 },
    { id: 19, title: "Registrar um experimento", description: "Documente dados, parâmetros, métricas e resultados de uma análise.", xp: 25 },
    { id: 20, title: "Entregar um projeto de dados", description: "Publique uma análise reproduzível com conclusões e visualizações.", xp: 25 },
  ],
  IA: [
    { id: 1, title: "Preparar o ambiente de IA", description: "Configure Python e uma biblioteca de aprendizado de máquina.", xp: 25 },
    { id: 2, title: "Preparar dados para treinamento", description: "Organize dados e separe conjuntos para treino e avaliação.", xp: 25 },
    { id: 3, title: "Treinar um primeiro modelo", description: "Treine um modelo simples de classificação ou regressão.", xp: 25 },
    { id: 4, title: "Experimentar uma rede neural", description: "Implemente uma rede neural pequena com PyTorch, TensorFlow ou Keras.", xp: 25 },
    { id: 5, title: "Avaliar o modelo", description: "Use métricas apropriadas e compare resultados com uma referência.", xp: 25 },
    { id: 6, title: "Testar um modelo de linguagem", description: "Experimente um modelo de linguagem e documente seus resultados.", xp: 25 },
    { id: 7, title: "Disponibilizar uma inferência", description: "Crie uma interface ou API simples para receber entradas e retornar previsões.", xp: 25 },
    { id: 8, title: "Revisar riscos e vieses", description: "Analise limitações, vieses e impactos do modelo antes de compartilhá-lo.", xp: 25 },
    { id: 9, title: "Implementar classificação", description: "Treine um modelo para atribuir categorias a exemplos.", xp: 25 },
    { id: 10, title: "Preparar imagens para um modelo", description: "Organize e transforme imagens para uma tarefa de visão computacional.", xp: 25 },
    { id: 11, title: "Experimentar embeddings", description: "Gere embeddings e compare a similaridade entre textos ou itens.", xp: 25 },
    { id: 12, title: "Construir uma busca semântica", description: "Recupere conteúdos relevantes usando embeddings e similaridade.", xp: 25 },
    { id: 13, title: "Ajustar hiperparâmetros", description: "Compare configurações de treinamento usando um conjunto de validação.", xp: 25 },
    { id: 14, title: "Controlar overfitting", description: "Identifique sinais de sobreajuste e aplique uma técnica de regularização.", xp: 25 },
    { id: 15, title: "Criar um fluxo RAG", description: "Combine recuperação de documentos e geração para responder com contexto.", xp: 25 },
    { id: 16, title: "Avaliar respostas de IA", description: "Defina critérios e avalie qualidade, relevância e precisão das respostas.", xp: 25 },
    { id: 17, title: "Monitorar custo e latência", description: "Meça tempo de resposta e uso de recursos de uma solução de IA.", xp: 25 },
    { id: 18, title: "Aplicar guardrails", description: "Valide entradas e saídas para reduzir respostas inadequadas ou inseguras.", xp: 25 },
    { id: 19, title: "Documentar um modelo", description: "Registre finalidade, dados, limitações e condições de uso do modelo.", xp: 25 },
    { id: 20, title: "Publicar uma solução de IA", description: "Disponibilize uma aplicação de IA e documente como utilizá-la.", xp: 25 },
  ],
  "Scrum Master": [
    { id: 1, title: "Estudar os fundamentos do Scrum", description: "Conheça responsabilidades, eventos, artefatos e compromissos do Scrum.", xp: 25 },
    { id: 2, title: "Facilitar uma Daily Scrum", description: "Pratique facilitar uma reunião curta com foco no progresso e impedimentos.", xp: 25 },
    { id: 3, title: "Apoiar o refinamento do backlog", description: "Ajude a esclarecer e dividir itens do backlog em trabalho compreensível.", xp: 25 },
    { id: 4, title: "Facilitar o planejamento da Sprint", description: "Conduza a definição de um objetivo e de um plano de Sprint.", xp: 25 },
    { id: 5, title: "Remover um impedimento", description: "Identifique um bloqueio da equipe e acompanhe sua resolução.", xp: 25 },
    { id: 6, title: "Conduzir uma Sprint Review", description: "Organize uma revisão do incremento e colete feedback dos participantes.", xp: 25 },
    { id: 7, title: "Facilitar uma retrospectiva", description: "Ajude a equipe a definir uma ação concreta de melhoria contínua.", xp: 25 },
    { id: 8, title: "Acompanhar a melhoria da equipe", description: "Revise uma métrica de fluxo ou de equipe sem usá-la para comparações individuais.", xp: 25 },
    { id: 9, title: "Apoiar a definição do Product Goal", description: "Ajude a equipe a compreender e manter um objetivo de produto claro.", xp: 25 },
    { id: 10, title: "Melhorar a Definition of Done", description: "Facilite um acordo de qualidade claro para incrementos concluídos.", xp: 25 },
    { id: 11, title: "Apoiar a colaboração com stakeholders", description: "Promova conversas produtivas entre equipe e pessoas interessadas.", xp: 25 },
    { id: 12, title: "Facilitar decisões em grupo", description: "Use uma técnica de facilitação para chegar a uma decisão compartilhada.", xp: 25 },
    { id: 13, title: "Mapear impedimentos recorrentes", description: "Identifique padrões de bloqueio e proponha ações para suas causas.", xp: 25 },
    { id: 14, title: "Promover autogerenciamento", description: "Ajude a equipe a assumir decisões e organizar o próprio trabalho.", xp: 25 },
    { id: 15, title: "Apoiar a previsão da Sprint", description: "Facilite uma conversa sobre capacidade, dependências e objetivo da Sprint.", xp: 25 },
    { id: 16, title: "Visualizar o fluxo de trabalho", description: "Torne etapas e bloqueios do trabalho visíveis para a equipe.", xp: 25 },
    { id: 17, title: "Facilitar um acordo de trabalho", description: "Ajude a equipe a definir acordos de colaboração e comunicação.", xp: 25 },
    { id: 18, title: "Acompanhar uma ação de melhoria", description: "Verifique o resultado de uma ação definida em retrospectiva.", xp: 25 },
    { id: 19, title: "Orientar sobre empirismo", description: "Ajude a equipe a inspecionar resultados e adaptar o plano com transparência.", xp: 25 },
    { id: 20, title: "Apoiar uma equipe sustentável", description: "Promova práticas que mantenham qualidade e ritmo de trabalho sustentáveis.", xp: 25 },
  ],
  "Product Manager": [
    { id: 1, title: "Identificar um problema de usuário", description: "Descreva um problema real e para quem ele é relevante.", xp: 25 },
    { id: 2, title: "Realizar uma entrevista", description: "Converse com usuários e registre necessidades sem induzir respostas.", xp: 25 },
    { id: 3, title: "Definir uma proposta de valor", description: "Explique qual benefício o produto oferece e para qual público.", xp: 25 },
    { id: 4, title: "Priorizar oportunidades", description: "Compare oportunidades usando critérios claros e alinhados ao objetivo.", xp: 25 },
    { id: 5, title: "Criar um roadmap", description: "Organize objetivos e resultados esperados em um roadmap de produto.", xp: 25 },
    { id: 6, title: "Escrever requisitos claros", description: "Transforme uma necessidade priorizada em requisitos e critérios de aceitação.", xp: 25 },
    { id: 7, title: "Validar uma solução", description: "Teste um protótipo ou hipótese com usuários e registre o aprendizado.", xp: 25 },
    { id: 8, title: "Definir métricas de sucesso", description: "Escolha indicadores que permitam acompanhar resultados para usuários e produto.", xp: 25 },
    { id: 9, title: "Mapear a jornada do usuário", description: "Descreva etapas, necessidades e dificuldades de uma experiência de usuário.", xp: 25 },
    { id: 10, title: "Analisar o mercado", description: "Pesquise alternativas e identifique oportunidades de diferenciação.", xp: 25 },
    { id: 11, title: "Segmentar usuários", description: "Agrupe usuários por necessidades ou comportamentos relevantes ao produto.", xp: 25 },
    { id: 12, title: "Escrever uma hipótese", description: "Relacione uma mudança proposta ao resultado esperado e como medi-lo.", xp: 25 },
    { id: 13, title: "Priorizar o backlog", description: "Ordene itens usando valor, esforço, risco ou outro critério explícito.", xp: 25 },
    { id: 14, title: "Desenhar um experimento", description: "Planeje um teste que permita validar uma hipótese de produto.", xp: 25 },
    { id: 15, title: "Analisar feedback de usuários", description: "Agrupe feedbacks e identifique necessidades recorrentes.", xp: 25 },
    { id: 16, title: "Definir um MVP", description: "Delimite a menor solução que permita testar uma hipótese importante.", xp: 25 },
    { id: 17, title: "Escrever uma visão de produto", description: "Comunique o público, a necessidade e o valor que o produto pretende entregar.", xp: 25 },
    { id: 18, title: "Acompanhar métricas de produto", description: "Analise indicadores de adoção, retenção ou conversão relacionados a um objetivo.", xp: 25 },
    { id: 19, title: "Comunicar uma decisão", description: "Registre contexto, alternativas e justificativa de uma decisão de produto.", xp: 25 },
    { id: 20, title: "Lançar uma melhoria", description: "Coordene a entrega de uma melhoria e avalie seus resultados após o lançamento.", xp: 25 },
  ],
};

export function getAchievementsForArea(area: string): Achievement[] {
  return achievementsByArea[area] ?? [];
}
